import RHGarden.LiFormal
import Mathlib.Analysis.Analytic.Constructions

#check Differentiable.analyticAt
#check AnalyticAt.hasFPowerSeriesAt
#check FormalMultilinearSeries.ofScalars
#check FormalMultilinearSeries.coeff
#check FormalMultilinearSeries.ofScalars_apply_eq
#check FormalMultilinearSeries.coeff_ofScalars
#check hasFPowerSeriesAt_iff
#check HasFPowerSeriesAt.comp
#check hasFPowerSeriesOnBall_inv_one_sub
#check analyticAt_inv_one_sub
#check Differentiable.comp
#check AnalyticAt.comp
#check Complex.one_div_one_sub_hasFPowerSeriesOnBall_zero
#check HasFPowerSeriesOnBall.hasFPowerSeriesAt
#check HasFPowerSeriesAt.eq_formalMultilinearSeries
#check FormalMultilinearSeries.ofScalars_sub
#check FormalMultilinearSeries.ofScalars_add
#check FormalMultilinearSeries.ofScalars_smul
#check HasFPowerSeriesAt.sub
#check hasFPowerSeriesAt_const
#check constFormalMultilinearSeries
#check HasFPowerSeriesAt.congr
#check AnalyticAt.clog
#check Complex.hasDerivAt_log
#check HasDerivAt.clog
#check Complex.deriv_log_comp_eq_logDeriv
#check hasFPowerSeriesAt_clog_one
#check hasFPowerSeriesAt_clog_one_add
#check PowerSeries.derivative_subst
#check PowerSeries.constantCoeff_iterate_derivative
#check PowerSeries.coeff_mul
#check PowerSeries.coeff_pow
#check Polynomial.coeff_one_add_X_pow
#check iteratedDeriv_comp_const_add
#check iteratedDeriv_comp_add_const
#check Finset.Nat.sum_antidiagonal_eq_sum_range_succ
#check Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk
