import RHGarden.SuzukiOnePercentData.Case1Part4

/- Copyright (c) 2026 Future Technologies Laboratory LLC.
Generated by scripts/suzuki-one-percent-witness.mjs. Every row, primality claim,
rational inequality and ordering is checked by Lean proof terms. -/
namespace RHGarden
set_option maxRecDepth 100000
set_option maxHeartbeats 0

def onePercentRows324431 : List SuzukiPrimeLowerRow :=
  onePercentRows324431_0 ++ (onePercentRows324431_1 ++ (onePercentRows324431_2 ++ (onePercentRows324431_3 ++ (onePercentRows324431_4 ++ (onePercentRows324431_5 ++ (onePercentRows324431_6 ++ (onePercentRows324431_7 ++ (onePercentRows324431_8 ++ (onePercentRows324431_9 ++ (onePercentRows324431_10 ++ (onePercentRows324431_11 ++ (onePercentRows324431_12 ++ (onePercentRows324431_13 ++ (onePercentRows324431_14 ++ (onePercentRows324431_15 ++ (onePercentRows324431_16 ++ (onePercentRows324431_17 ++ (onePercentRows324431_18))))))))))))))))))

theorem onePercentRows324431_valid : ∀ r ∈ onePercentRows324431, r.Valid 324431 339360 (12689828147 / 1000000000) := by
  simp only [onePercentRows324431, List.forall_mem_append]
  exact ⟨onePercentRows324431_0_valid, onePercentRows324431_1_valid, onePercentRows324431_2_valid, onePercentRows324431_3_valid, onePercentRows324431_4_valid, onePercentRows324431_5_valid, onePercentRows324431_6_valid, onePercentRows324431_7_valid, onePercentRows324431_8_valid, onePercentRows324431_9_valid, onePercentRows324431_10_valid, onePercentRows324431_11_valid, onePercentRows324431_12_valid, onePercentRows324431_13_valid, onePercentRows324431_14_valid, onePercentRows324431_15_valid, onePercentRows324431_16_valid, onePercentRows324431_17_valid, onePercentRows324431_18_valid⟩

theorem onePercentRows324431_chain : (onePercentRows324431.map SuzukiPrimeLowerRow.prime).IsChain (· < ·) := by
  simp only [onePercentRows324431, List.map_append, List.isChain_append]
  norm_num [onePercentRows324431_0, onePercentRows324431_1, onePercentRows324431_2, onePercentRows324431_3, onePercentRows324431_4, onePercentRows324431_5, onePercentRows324431_6, onePercentRows324431_7, onePercentRows324431_8, onePercentRows324431_9, onePercentRows324431_10, onePercentRows324431_11, onePercentRows324431_12, onePercentRows324431_13, onePercentRows324431_14, onePercentRows324431_15, onePercentRows324431_16, onePercentRows324431_17, onePercentRows324431_18, List.isChain_cons_cons]

theorem onePercentRows324431_sum : (onePercentRows324431.map SuzukiPrimeLowerRow.weightLowerNumerator).sum = 592287163908 := by
  norm_num [onePercentRows324431, List.map_append, List.sum_append, onePercentRows324431_0, onePercentRows324431_1, onePercentRows324431_2, onePercentRows324431_3, onePercentRows324431_4, onePercentRows324431_5, onePercentRows324431_6, onePercentRows324431_7, onePercentRows324431_8, onePercentRows324431_9, onePercentRows324431_10, onePercentRows324431_11, onePercentRows324431_12, onePercentRows324431_13, onePercentRows324431_14, onePercentRows324431_15, onePercentRows324431_16, onePercentRows324431_17, onePercentRows324431_18]

end RHGarden
