name:                 rh-garden
version:              0.1.0.0
visibility:           public
id:                   rh-garden-0.1.0.0-inplace
key:                  rh-garden-0.1.0.0-inplace
license:              BSD-3-Clause
synopsis:
    Typed representation-graph proof search for the Riemann Hypothesis

category:             Mathematics
abi:                  inplace
exposed:              True
exposed-modules:
    RHGarden.Algebra RHGarden.Core RHGarden.Evidence RHGarden.Mobius
    RHGarden.Registry RHGarden.Representation RHGarden.Search

import-dirs:
    Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.cabal-work\build\x86_64-windows\ghc-9.10.3\rh-garden-0.1.0.0\build

library-dirs:
    Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.cabal-work\build\x86_64-windows\ghc-9.10.3\rh-garden-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.cabal-work\build\x86_64-windows\ghc-9.10.3\rh-garden-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.cabal-work\build\x86_64-windows\ghc-9.10.3\rh-garden-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

data-dir:             Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.
hs-libraries:         HSrh-garden-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:              base-4.20.2.0-39f9 containers-0.7-c2a5
haddock-interfaces:
    Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.cabal-work\build\x86_64-windows\ghc-9.10.3\rh-garden-0.1.0.0\doc\html\rh-garden\rh-garden.haddock

haddock-html:
    Z:\OneDrive\Projects\FTL\Riemann\rh-garden\.cabal-work\build\x86_64-windows\ghc-9.10.3\rh-garden-0.1.0.0\doc\html\rh-garden
